services:
  # Fabric coordinator - routes queries across shards
  neo4j-fabric:
    image: neo4j:4.4-enterprise
    container_name: neo4j-fabric
    mem_limit: 4g
    memswap_limit: 4g
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_routing_enabled=true
      - NEO4J_dbms_routing_default_router=SERVER
      - NEO4J_fabric_database_name=fabric
      - NEO4J_fabric_graph_0_name=persons
      - NEO4J_fabric_graph_0_uri=neo4j://neo4j-persons:7687
      - NEO4J_fabric_graph_0_database=persons
      - NEO4J_fabric_graph_1_name=forums
      - NEO4J_fabric_graph_1_uri=neo4j://neo4j-forums:7687
      - NEO4J_fabric_graph_1_database=forums
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
    volumes:
      - neo4j-data-main:/data
      - neo4j-logs-main:/logs
      - ./ldbc_snb_interactive_v2_impls/ldbc-snb-sf1:/var/lib/neo4j/import
    networks:
      - neo4j-network

  neo4j-persons:
    image: neo4j:4.4-enterprise
    container_name: neo4j-persons
    mem_limit: 4g
    memswap_limit: 4g
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j-persons:7687
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
    volumes:
      - neo4j-data-persons:/data
      - neo4j-logs-persons:/logs
      - ./ldbc_snb_interactive_v2_impls/ldbc-snb-sf1:/var/lib/neo4j/import
    networks:
      - neo4j-network

  neo4j-forums:
    image: neo4j:4.4-enterprise
    container_name: neo4j-forums
    mem_limit: 6g
    memswap_limit: 6g
    ports:
      - "7476:7474"
      - "7689:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j-forums:7687
      - NEO4J_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
      - NEO4J_dbms_recovery_fail__on__corruption=false
      - NEO4J_dbms_recovery_fail__on__missing__files=false
      - NEO4J_dbms_logs_debug_recovery=true
    volumes:
      - neo4j-data-forums:/data
      - neo4j-logs-forums:/logs
      - ./ldbc_snb_interactive_v2_impls/ldbc-snb-sf1:/var/lib/neo4j/import
    networks:
      - neo4j-network

  # Recovery service for forums database
  neo4j-forums-recovery:
    image: neo4j:4.4-enterprise
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_recovery_fail__on__corruption=false
    volumes:
      - neo4j-data-forums:/data
    command: neo4j-admin check-consistency --database=forums --fix-inconsistencies
    profiles:
      - recovery

volumes:
  neo4j-data-main:
  neo4j-logs-main:
  neo4j-data-persons:
  neo4j-logs-persons:
  neo4j-data-forums:
  neo4j-logs-forums:

networks:
  neo4j-network: